apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "geth-swap.fullname" . }}-setupcontracts
  labels:
    {{- include "geth-swap.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: setup
        image: ethersphere/setup-contracts:latest
        env:
          - name: BACKEND
            value: "http://{{ include "geth-swap.fullname" . }}:8545"
          - name: BZZACCOUNTS
            value: {{ .Values.swap.bzzaccounts | join " " }}
        command:
          - sh
          - -ac
          - >
            while ! curl $BACKEND; do sleep 1; done;
            bash deploy.sh
      restartPolicy: Never
