{{- if and .Values.beeConfig.usePasswordFile (not .Values.beeConfig.existingSecret) -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bee.fullname" . }}
  labels:
    {{- include "bee.labels" . | nindent 4 }}
type: Opaque
data:
    password: {{ include "bee.password" . | b64enc | quote }}
    
{{- end -}}
{{- if and .Values.libp2pSettings.enabled -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bee.fullname" . }}-libp2p
  labels:
    {{- include "bee.labels" . | nindent 4 }}
type: Opaque
stringData:
  libp2pKeys: |-
    {{- range $key, $val := .Values.libp2pSettings.libp2pKeys }}
    {{ $key }}: {{ $val }}
    {{- end }}
    
{{- end -}}